name: Check, Build and Test

on:
  pull_request:

# # Debug setup:
# env:
#   OGDF_UTILS_PREQUEL: "set -x"
#   CCACHE_DEBUG: 1
#   CCACHE_DEBUGDIR: ${{ github.workspace }}/ccache-debug

jobs:
  style:
    name: "Check code style"
    runs-on: ubuntu-latest
    container: docker.io/ogdf/clang:15
    steps:
      - name: "Add workspace as a safe directory in containers"
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - run: util/style/test_clang_format.sh
      - run: util/style/test_eols.sh
      - run: util/style/test_number_newlines.sh
      - run: util/style/test_line_length.sh
      - run: util/style/test_tabs.sh
      - run: util/style/test_macros.sh
      - run: util/style/test_license.sh
      - run: util/style/test_no_typedefs.sh
      - run: util/style/test_no_enums.sh
      - run: util/style/test_indent_comments.sh

  dirs:
    name: "Check directory structure"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test directory structure
        run: util/test_directory_structure.sh

  docs:
    name: "Check Doxygen"
    runs-on: ubuntu-latest
    container: docker.io/ogdf/clang:15
    steps:
      - uses: actions/checkout@v4
      - run: util/test_doxygen.sh

  self-sufficiency:
    name: "Test self-sufficiency"
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -v"
    steps:
      - uses: actions/checkout@v4
      - name: Set-up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
      - name: Test self-sufficiency
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          util/test_self-sufficiency.sh
      - uses: actions/upload-artifact@v4
        name: Upload ccache debug info
        if: ${{ env.CCACHE_DEBUG == 1 }}
        with:
          name: ${{ github.job }}
          path: ${{ github.workspace }}/ccache-debug


  static-analysis:
    name: "Static Analysis"
    runs-on: ubuntu-latest
    container: docker.io/ogdf/clang:15
    needs: [ style, dirs, self-sufficiency, docs ]
    env:
      CCACHE_COMPILERCHECK: "%compiler% -v"
    steps:
      - name: "Add workspace as a safe directory in containers"
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - name: Set-up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
      - name: Set-up clang-tidy cache
        uses: actions/cache@v4
        with:
          path: .ctcache
          key: clang-tidy-cache
      - name: Run analysis
        env:
          CTCACHE_DIR: .ctcache
          # CTCACHE_DUMP: ${{ env.CCACHE_DEBUG }} # defining the var is enough to enable
        run: |
          util/test_static_analysis.sh -DOGDF_ARCH=haswell -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          find .ctcache -mtime +7 -exec rm -rv \{} \;
          cat static-analysis/clang-tidy.txt | python3 -m clang_tidy_converter sq > static-analysis/clang-tidy.json
        shell: bash
      - name: Report unused files
        run: cat static-analysis/unused-headers.txt
      - name: Save PR number to file
        run: |
          echo ${{ github.event.number }} > static-analysis/PR_NUMBER.txt
          cat static-analysis/PR_NUMBER.txt
      - name: Store static analysis results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: static-analysis
          path: static-analysis/
      - uses: actions/upload-artifact@v4
        name: Upload ccache debug info
        if: ${{ env.CCACHE_DEBUG == 1 }}
        with:
          name: ${{ github.job }}
          path: ${{ github.workspace }}/ccache-debug

  coverage:
    name: "Analyze Test Coverage"
    runs-on: ubuntu-latest
    container: docker.io/ogdf/clang:15
    needs: [ style, dirs, self-sufficiency, docs ]
    env:
      CCACHE_COMPILERCHECK: "%compiler% -v"
    steps:
      - name: "Add workspace as a safe directory in containers"
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - name: Set-up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}
      - name: Run analysis
        run: |
          util/test_coverage.sh -DOGDF_ARCH=haswell -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        shell: bash
      - name: Store coverage data
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage
          path: coverage/
      - uses: actions/upload-artifact@v4
        name: Upload ccache debug info
        if: ${{ env.CCACHE_DEBUG == 1 }}
        with:
          name: ${{ github.job }}
          path: ${{ github.workspace }}/ccache-debug


  build-linux:
    name: "Test ${{ matrix.mode }} build on Linux with ${{ matrix.compiler }}"
    strategy:
      matrix:
        mode: [ debug, release ]
        compiler: [ 'gcc:9', 'gcc:13', 'clang:15' ]
    runs-on: ubuntu-latest
    container: docker.io/ogdf/${{ matrix.compiler }}
    needs: [ style, dirs, self-sufficiency, docs ]
    env:
      CCACHE_COMPILERCHECK: "%compiler% -v"
    steps:
      - name: Set compiler name
        run: |
          GH_COMPILER_NAME="${{ matrix.compiler }}"
          GH_COMPILER_NAME="${GH_COMPILER_NAME//:}"
          echo "GH_COMPILER_NAME=${GH_COMPILER_NAME}" >> "$GITHUB_ENV"
        shell: bash
      - name: "Add workspace as a safe directory in containers"
        run: git config --system --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - name: Set-up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.compiler }}-${{ matrix.mode }}
      - name: Check ccache version
        run: ccache --version
      - name: Check CPU model
        run: lscpu
      - name: Test ${{ matrix.mode }} build with ${{ matrix.compiler }} and run
        run: |
          util/test_build_and_run.sh \
            ${{ matrix.compiler == 'gcc:9' && 'dynamic' || 'static' }} \
            ${{ matrix.mode }} \
            ${{ startsWith(matrix.compiler, 'gcc') && 'gcc' || 'clang' }} \
            default_s \
            ${{ matrix.compiler != 'clang:15' && '-DOGDF_INCLUDE_CGAL=ON -DOGDF_USE_ASSERT_EXCEPTIONS=ON' || '' }} \
            -DOGDF_USE_ASSERT_EXCEPTIONS=ON -DOGDF_ARCH=haswell \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        # extra flags used when collecting coverage (on clang:15) are disabled here
        # ---
        # see "Cloud hosts used by GitHub-hosted runners" in the GH Actions docs
        # for the oldest used microarchitecture to use with OGDF_ARCH
      - uses: actions/upload-artifact@v4
        name: Upload ccache debug info
        if: ${{ env.CCACHE_DEBUG == 1 }}
        with:
          name: ${{ github.job }}-${{ env.GH_COMPILER_NAME }}-${{ matrix.mode }}
          path: ${{ github.workspace }}/ccache-debug

  build-macos:
    name: "Test ${{ matrix.mode }} build on MacOS"
    strategy:
      matrix:
        mode: [ debug, release ]
    runs-on: macos-latest
    needs: [ style, dirs, self-sufficiency, docs ]
    steps:
      - uses: actions/checkout@v4
      - run: brew install coreutils findutils
      - name: Set-up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.mode }}
      - name: Check CPU model
        run: |
          uname -av
          sysctl machdep.cpu
          system_profiler system_profiler SPSoftwareDataType SPHardwareDataType
      - name: Test ${{ matrix.mode }} build and run
        run: |
          util/test_build_and_run.sh \
            static \
            ${{ matrix.mode }} \
            default_c \
            default_s \
            -DOGDF_USE_ASSERT_EXCEPTIONS=ON -DOGDF_ARCH=ivybridge \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        # ivybridge is the oldest arch we encountered from SIGILL ccaching problems
      - uses: actions/upload-artifact@v4
        name: Upload ccache debug info
        if: ${{ env.CCACHE_DEBUG == 1 }}
        with:
          name: ${{ github.job }}-${{ matrix.mode }}
          path: ${{ github.workspace }}/ccache-debug

  build-windows:
    name: "Test ${{ matrix.mode }} build on Windows"
    strategy:
      matrix:
        mode: [ debug, release ]
    runs-on: windows-latest
    needs: [ style, dirs, self-sufficiency, docs ]
    steps:
      - uses: actions/checkout@v4
      - uses: microsoft/setup-msbuild@v2
      - name: Set-up ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.mode }}
      - name: Test ${{ matrix.mode }} build and run
        run: powershell util\test_build_and_run.ps1 ${{ matrix.mode == 'debug' && '-debug' }}
        env:
          CMAKE_C_COMPILER_LAUNCHER: ccache.exe
          CMAKE_CXX_COMPILER_LAUNCHER: ccache.exe
      - uses: actions/upload-artifact@v4
        name: Upload ccache debug info
        if: ${{ env.CCACHE_DEBUG == 1 }}
        with:
          name: ${{ github.job }}-${{ matrix.mode }}
          path: ${{ github.workspace }}/ccache-debug


  # this is mostly used to keep the required status checks for PR merging simple
  summary:
    needs: [ build-linux, build-macos, build-windows, static-analysis, coverage ]
    name: "All tests succeeded"
    runs-on: ubuntu-latest
    steps:
      - run: echo "Everything worked!"
        shell: bash
